
@echo off

REM !!! Generated by the fmp-cli 1.86.0.  DO NOT EDIT!

md DummyLayoutUnderwaterWorld\Assets\3rd\fmp-xtc-dummylayoutunderwaterworld

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-dummylayoutunderwaterworld-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\DummyLayoutUnderwaterWorld\Assets\3rd\fmp-xtc-dummylayoutunderwaterworld\
